### ISSUE TITLE
Documentation of feed options

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#108]
I've just reorganized the wiki's presentation of feed options so that we can use it to create clearer documentation. There are now three pages, one each devoted to [rss/atom](https://github.com/CenterForOpenScience/SHARE/wiki/Consuming-with-Atom-and-RSS), [pubsubhubbub](https://github.com/CenterForOpenScience/SHARE/wiki/Consuming-with-PubSubHubbub), and [resourcesync](https://github.com/CenterForOpenScience/SHARE/wiki/Consuming-with-ResourceSync).

While the structure is clearer now, these pages themselves have a ways to go before they are adequate documentation. We have to put ourselves into our reader's shoes. They are likely people who have not dealt with either PubSubHubbub or ResourceSync yet, and we could stand to be a lot clearer about how these technologies are being used to provide notification feeds.

Please take a look at these pages and add clarity and depth if you can!

**Comment by efc** [comment]
This is exactly the kind of thing we need, Erin! Excellent!

I've been banging around all morning today and finding that I have a huge learning curve. Then I happened to notice you'd put this up three days ago and found much of what I was struggling with clearly illuminated. For example, I just could not figure out how to get a simple elastic search query to the NS, boom, you've got that here.

Just what I needed.

**Comment by efc** [comment]
@erinspace, a question... What guarantees that we are getting the most recent additions with these queries? In your example above, how can I be sure these are the 8 most recent additions to the NS from arXiv? I don't see anything in the query to enforce this ordering. Is it somewhere else implicit in scrapi or Elastic Search?

**Comment by erinspace** [comment]
Hi @efc , good point! I don't seem to consistently be getting the most recent titles. Will keep exploring this and update the notebook accordingly.

**Comment by efc** [comment]
@erinspace sent me email explaining this as follows...

> Specifying that elasticsearch sort by dateUpdated gives the most recent records. 
> 
> In your example query, adding ```"sort": { "dateUpdated": { "order": "desc" }}```  will give you recent results. So, your query will look like this: 

```python
query_match_all = '''
{
    "size" : 1,
    "sort" : { "dateUpdated" : { "order" : "desc" } },
    "filter" : {
        "missing" : { "field" : "isResource" }
    }
}
'''
```
However, I am not sure this quite does the trick.

First of all, right now when I use this technique I get a most recent item dated "2015-03-01" which is both in the future and not a properly formatted date (our dates usually have times on them, though granted usually lots of zeros since we don't know the real time).

In fact, check out the results of this script...

```python
import json
import requests
OSF_APP_URL = 'https://share-dev.osf.io/api/v1/app/6qajn/?raw=True'
HEADERS = {'Content-Type': 'application/json'}

query_match_all = '''
{
    "size" : 15,
    "sort" : { "dateUpdated" : { "order" : "desc" } },
    "filter" : {
        "missing" : { "field" : "isResource" }
    }
}
'''
result = requests.post(OSF_APP_URL, headers=HEADERS, data=query_match_all, verify=False).json()
try:
    for record in result['hits']['hits']:
        s = record['_source']
        print "id %s u %s c %s fin %s" % ( record['_id'], s['dateUpdated'], s['dateCreated'], s['timestamps']['consumeFinished'] )
except KeyError:
    print json.dumps(result, indent=4)
```
Which results in...
```
id 54a342e7b5e9d743536f0da7 u 2015-03-01 c 2015-03-01 fin 2014-12-31T00:01:17.449590
id 54a342eab5e9d743516f0c90 u 2015-03-01 c 2015-03-01 fin 2014-12-31T00:01:17.449590
id 54a342f0b5e9d7434f6efe87 u 2015-02-15 c 2015-02-15 fin 2014-12-31T00:01:17.449590
id 54a5f851b5e9d743536f30cb u 2015-02-15 c 2015-02-15 fin 2015-01-02T00:16:07.042734
id 54a49471b5e9d743536f152d u 2015-02 c 2015-02 fin 2015-01-01T00:06:57.238386
id 54a341fdb5e9d743536f0c81 u 2015-02 c 2015-02 fin 2014-12-31T00:01:17.449590
id 54a49471b5e9d743516f13a9 u 2015-02 c 2015-02 fin 2015-01-01T00:06:57.238386
id 54a4946eb5e9d743536f152a u 2015-02 c 2015-02 fin 2015-01-01T00:06:57.238386
id 54a49470b5e9d7434d6efff8 u 2015-02 c 2015-02 fin 2015-01-01T00:06:57.238386
id 54a342ebb5e9d743516f0c92 u 2015-02-01 c 2015-02-01 fin 2014-12-31T00:01:17.449590
id 54a4946eb5e9d743516f13a4 u 2015-02 c 2015-02 fin 2015-01-01T00:06:57.238386
id 54a9e5cab5e9d743536f37d0 u 2015-01-04T03:43:16+00:00 c 2014-08-29T07:00:00+00:00 fin 2015-01-04T23:59:00.823289
id 54a88290b5e9d743536f3411 u 2015-01-03T23:17:00 c 2015-01-03T23:17:00 fin 2015-01-04T00:00:02.386873
id 54a88291b5e9d743516f3164 u 2015-01-03T19:50:00 c 2015-01-03T19:49:00 fin 2015-01-04T00:00:02.386873
id 54a88291b5e9d743516f3165 u 2015-01-03T19:21:00 c 2015-01-03T19:21:00 fin 2015-01-04T00:00:02.386873
```
Note it is not until line 13 that the ```dateUpdated``` start making any sense.

I am also not clear on the source of the ```dateUpdated```? What, exactly, is that date? In all of these entries the ```dateCreated``` and ```dateUpdated``` seem to be the same, and all of the last three of these records share the exact same ```consumeFinished``` time.

Finally, even if ```dateUpdated``` is the right way to do this, I am not clear on how I would use this to guarantee that I am picking up everything since the last time I checked. I suppose I could look at the ```dateUpdated``` of the first record I get back this way and in my next query limit only to ```dateUpdated``` that are greater than this. But would it be possible for the system to add a record with a ```dateUpdated``` less than this after I'd done my first query? Again, this comes down to not being clear on what, exactly, the ```dateUpdated``` is supposed to represent.

**Comment by erinspace** [comment]
Feed documentation updated and available here: https://osf.io/wur56/wiki/Feed%20Options/, along with beta changes that solve these duplicate problems.
