### ISSUE TITLE
RSS entries without sources?

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#115]
I've been playing around with the RSS feed and finding a number of entries without any source field in the description. See the list below, which is pull from RSS data with a lastBuildDate of ```2014-12-04 14:48:09.978009```.

The sources I found in this pull from RSS included {'dataone': 133, 'spdataverse': 2, 'upenn': 22, 'pushtest': 2, 'no source': 62, 'cmu': 2, 'stcloud': 1, 'mit': 25, 'trinity': 1}

That "no source" is from records that were missing the "source" element in their description. The "link" for these records are in the list below. They seem to be from quite a few of our providers (I'm not worried about the "anexample" one, which seems to be from push testing), most of whom also have records that included sources.

Any idea why these seem to be sneaking through without the source being attributed?

http://digitalcommons.trinity.edu/psych_faculty/76
http://hdl.handle.net/10864/10334
http://hdl.handle.net/1721.1/92017
http://hdl.handle.net/1721.1/92025
http://hdl.handle.net/1721.1/92026
http://hdl.handle.net/1721.1/92029
http://hdl.handle.net/1721.1/92030
http://repository.cmu.edu/dissertations/404
http://repository.cmu.edu/dissertations/405
http://repository.stcloudstate.edu/lrs_facpubs/42
http://repository.upenn.edu/bellwether/vol1/iss80/13
http://repository.upenn.edu/bellwether/vol1/iss80/16
http://repository.upenn.edu/bellwether/vol1/iss80/2
http://repository.upenn.edu/bellwether/vol1/iss80/4
http://repository.upenn.edu/bellwether/vol1/iss80/6
http://repository.upenn.edu/bellwether/vol1/iss80/8
http://www.anexample.org/article
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.0r7g4%3Fver%3D2014-12-03T13%3A10%3A26.351-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.116td%3Fver%3D2014-12-03T11%3A40%3A41.868-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.16pj3%2F1%3Fver%3D2014-12-03T12%3A44%3A49.623-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.16pj3%3Fver%3D2014-12-03T12%3A44%3A43.282-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.1jv55%3Fver%3D2014-12-03T13%3A58%3A10.441-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.204bc%3Fver%3D2014-12-03T11%3A59%3A42.415-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.2g203%3Fver%3D2014-12-03T14%3A34%3A03.734-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.46dt3%3Fver%3D2014-12-03T12%3A50%3A31.598-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.46dt3%3Fver%3D2014-12-03T12%3A52%3A40.684-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.4k5st%2F1%3Fver%3D2014-12-03T12%3A51%3A25.187-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.4k5st%3Fver%3D2014-12-03T12%3A51%3A15.695-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.55203%3Fver%3D2014-12-03T11%3A05%3A27.683-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.5tp2v%3Fver%3D2014-12-03T13%3A04%3A26.817-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.5tp41%3Fver%3D2014-12-03T10%3A38%3A15.190-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.6bp0f%3Fver%3D2014-12-03T11%3A06%3A53.383-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.7c06s%3Fver%3D2014-12-03T13%3A22%3A23.566-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.7tv47%3Fver%3D2014-12-03T12%3A27%3A41.151-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.83qh4%3Fver%3D2014-12-03T13%3A14%3A47.170-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.86gm0%3Fver%3D2014-12-03T14%3A04%3A12.200-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.90005%3Fver%3D2014-12-03T12%3A29%3A26.717-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.96cp4%3Fver%3D2014-12-03T13%3A47%3A33.863-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.f4114%2F3%3Fver%3D2014-12-03T10%3A52%3A45.022-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.f4114%2F4%3Fver%3D2014-12-03T10%3A52%3A54.400-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.f4114%3Fver%3D2014-12-03T10%3A52%3A11.393-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.g6q07%2F1%3Fver%3D2014-12-03T14%3A35%3A12.567-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.g6q07%3Fver%3D2014-12-03T14%3A34%3A42.792-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.h4n48%2F1%3Fver%3D2014-12-03T12%3A39%3A57.230-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.h4n48%3Fver%3D2014-12-03T12%3A39%3A41.304-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.h7m7t%3Fver%3D2014-12-03T12%3A56%3A48.590-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.hc445%2F1%3Fver%3D2014-12-03T15%3A58%3A51.446-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.hc445%2F2%3Fver%3D2014-12-03T15%3A59%3A02.130-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.hc445%3Fver%3D2014-12-03T15%3A58%3A41.446-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.j96r3%3Fver%3D2014-12-03T13%3A01%3A23.526-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.jc0df%2F1%3Fver%3D2014-12-03T14%3A45%3A47.454-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.jc0df%3Fver%3D2014-12-03T14%3A19%3A52.337-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.k5786%3Fver%3D2014-12-03T14%3A57%3A03.192-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.m9160%2F1%3Fver%3D2014-12-03T15%3A46%3A15.232-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.m9160%3Fver%3D2014-12-03T15%3A45%3A57.015-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.p1s20%3Fver%3D2014-12-03T13%3A13%3A21.354-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.qn474%2F5%3Fver%3D2014-12-03T15%3A54%3A42.890-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.qn474%2F6%3Fver%3D2014-12-03T15%3A54%3A58.861-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.qn474%2F8%3Fver%3D2014-12-03T15%3A55%3A20.228-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.qn474%3Fver%3D2014-12-03T15%3A53%3A47.273-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.tm8k3%3Fver%3D2014-12-03T13%3A12%3A04.179-05%3A00
https://cn.dataone.org/cn/v1/resolve/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.vp743%3Fver%3D2014-12-03T12%3A33%3A27.309-05%3A00

**Comment by efc** [comment]
A few more questions about the "resource records." I'm not necessarily looking for quick answers, I just don't want to forget the questions!

How does "isResource" help filter these records, since more commonly I imagine we would need to find those things that are NOT resources. Since the "isResource" field is not even present in non-resource records, this makes filtering a bit awkward (though doable). If the dataset is to have records of multiple "types" mixed together, wouldn't it be more flexible to have a "type" field with entries like "event" and "resource"? That would also allow us to grow beyond two types, if we ever needed to.

I've found it is easier to just filter for items that have an actual source. That technique, however, leaves me wondering whether all resources are sourceless? And why don't the resource records have a "source" since they clearly come from a source?

How does additional information brought to the notification service though these resource records get incorporated into results? What kind of post-query processing do you envision to tie events and their halo of collision-inspired resources together?

**Comment by JeffSpies** [comment]
We're removing events with isResource from default output. As such, closing.
