### ISSUE TITLE
Harvester Source Names

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#116]
I just got the following query from Leanne on the Scholars Portal team:

> I'm having difficulty using the RSS to query Scholars Portal as a source. Do you know what our source abbreviation is? Works fine for 'plos' as given in the example. 

Our choices of names for sources seems rather arbitrary and there really is no good way, other than a somewhat manual listing as I see in one iPython notebook, to keep track of them.

I wonder if we should choose a more systematic method of determining these source names? A few months back I changed the naming of our provider documents to use [reverse domains](https://github.com/CenterForOpenScience/SHARE/issues/86). Might something similar work for source names and be more predictable?

At a minimum we need a reliable way to look up these source names. Maybe once the harvesters are written the details like a pointer to the harvester code and the source name used for the harvester could be added to the [provider documents](https://github.com/CenterForOpenScience/SHARE/tree/master/providers)?

**Comment by JeffSpies** [comment]
For our use-case, what is the advantage of reversed domains over actual domains?
