### ISSUE TITLE
A feed that guarantees I see every event

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#121]
As I understand it, the RSS feed may miss events because it will max out at 250 events at a time, and from time to time we have more than 250 flow through the NS between updates.

Furthermore, I believe the PubSubHubbub feed is based on the RSS "document" being updated, though I am not sure if this is correct. ResourceSync is built upon PubSubHubbub as well.

I am wondering if any of our feed mechanisms actually guarantee that I would see every event flowing through the NS?

If so, we need to document how to do that. If not, we need to create such a feed mechanism prior to the beta release. This is the mechanism I'd like to share with some of our not-super-tech-savvy participants who wanted to monitor the flow, so we will have to make it relatively easy to use.

**Comment by JeffSpies** [comment]
We will only be able to provide content based on the output format's spec. ResourceSync, at least, should be able to provide this functionality. We need to confirm that is the case; if not, research on another technology is recommended.
