### ISSUE TITLE
Pretty RSS feed

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#122]
Before the beta we will want to create a pretty version of the RSS feed. In fact, the "pretty" version will probably be our default RSS feed, though some alternate version with JSON embedded might be useful for experimentation beyond the beta.

**Comment by efc** [comment]
Did something change with this lately? I can't get at the JSON version of the RSS feed.

```
$ curl "https://share-dev.osf.io/api/v1/app/6qajn/rss/extended%3DTrue/"
{"code": 401, "referrer": null, "message_short": "Unauthorized", "message_long": "You must <a href=\"/login/\">log in</a> to access this resource."}
```

**Comment by efc** [comment]
Oops, I thought I found my error, missing "?" but only found including the "?" produced a different error...

```
$ curl "https://share-dev.osf.io/api/v1/app/6qajn/rss/?extended=True"
OSF was unable to resolve your request. If this issue persists, please report it to <a href="mailto:support@osf.io">support@osf.io</a>.
```

**Comment by erinspace** [comment]
RSS issue should be fixed now, sorry for the momentary hiccup!
