### ISSUE TITLE
Self Registration of providers and consumers

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#123]
For the beta release we need to make self registration of new providers and consumers possible. This will require...

- language for metadata rights (even if not quite a CC0 license) that new providers can agree to
- authentication mechanism for provision (via push) and consumption (for full streams, at least)
- a workflow to follow up registration with creation of harvester, follow up with questions raised, etc.

**Comment by JeffSpies** [comment]
Minimal product:

[ ] Form for provider to fill out
[ ] Human contacts that provider for confirmation
[ ] Human references data from that form in an issue (or some other mechanism)

**Comment by erinspace** [comment]
This has been developed and is accessible on staging at https://staging.osf.io/share/registration/
