### ISSUE TITLE
[metadata] [spec] Schema udpate

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#126]
Our current [metadata schema](https://github.com/CenterForOpenScience/SHARE/wiki/SHARE-schema) is a "placeholder" in that it does not really attempt tot facilitate to the [user stories](https://docs.google.com/document/d/1LWbmvF5v24f7z_VwyHxxkLlbEA4HcDs48p_i9Uui-DI/edit) we have outlined for SHARE (note, those stories themselves are not complete yet). My intention is that we use the work of [COAR OAIO (Open Access Interoperability) Guidelines](https://www.coar-repositories.org/news-media/coar-casrai-and-regional-repository-networks-launch-international-group-to-improve-interoperability/) to inform both our metadata schema and a set of recommendations we make to SHARE Enabling institutions for their own metadata. However, that effort will likely not pay off until after our beta gets underway. 

Meanwhile, before we roll out the beta we need to improve our metadata scheme so that it at least includes essential components (especially identifiers) required for our user stories and clear documentation about its own requirements. It might, for example, be possible to put the documentation in the form of a JSON-LD context document.

Maybe we could use this issue to hash out some of the alternatives possible for this beta metadata schema.

**Comment by erinspace** [comment]
Beta schema available at https://github.com/JeffSpies/SHARE-Schema
