### ISSUE TITLE
[content provider] Valparaiso

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#128]
I have just completed the [provider document for Valparaiso University's ValpoScholar](https://github.com/CenterForOpenScience/SHARE/blob/master/providers/edu.valpo.md). This is a bepress repository with mixed content, so we should only harvest material in the collections and communities specified in the list supplied in by Jon at Valparaiso. I apologize for the tardiness of getting this provider added. I discovered I'd overlooked Jon's submission of the list in October when doing some year-end cleanup in January. This oversight was entirely my fault.

**Comment by erinspace** [comment]
Harvester has been written and going into production soon! 

https://github.com/erinspace/ValpoScholar

**Comment by efc** [comment]
Sorry to reopen this one, @erinspace, but I have not see any data from Valparaiso yet. Is the harvester working and just not finding anything? or is something else up?

**Comment by erinspace** [comment]
This has been written, and is working locally, but we're waiting on some major updates to scrapi backend before pushing to production! Sorry to close prematurely!  Will close when everything is officially running in production.

**Comment by erinspace** [comment]
Now live, see results at https://osf.io/share/?q=source:valposcholar
