### ISSUE TITLE
[output] [spec] ATOM

### ISSUE THREAD

**Issue by JeffSpies** [CenterForOpenScience/SHARE#130]
Fill in what the /rss route will return.

- [ ] #131

**Comment by efc** [comment]
I think we really mean what the /atom route would return?

In any case, my feeling is the /rss and /atom route should be pretty much identical in what they return. They only differ in the format of the records returned. Atom has a bit more flexibility in the fields we could offer the user.

**Comment by erinspace** [comment]
Atom feed developed, sent to pre-beta testers in the SHARE working groups and deployed at https://osf.io/share/atom/, closing this issue for now.  We can re-open individual issues should they arise.
