### ISSUE TITLE
Lack of explicit time zones for timestamps

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#136]
The timestamps in our normalized data do not include an explicit timezone. The ISO standard states that if a timestamp in ISO format lacks an explicit timezone, then local time (in our case Eastern Time) should be assumed. However, it appears to me that the timestamps are being recorded in UTC not Eastern Time. If this is the case, then they should include an explicit timezone of "Z" or "+00" on the end to make this clear.

I think an explicit timezone would be a good idea, even if the times are meant to be "local" since our whole mission is to rebroadcast this data. We have no idea what will be considered "local" on the receiving end.

**Comment by fabianvf** [comment]
This is an excellent point. I'll make sure it gets updated.

**Comment by erinspace** [comment]
this is fixed!
