### ISSUE TITLE
id.url field needs new mapping

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#137]
It appears to me that the id.url field in our normalized records is being "analyzed" by elastic search. The result is that it is hard to detect duplicate URLs using aggregations. 

For an example, give this elastic search request a try...

```
{
    "size": 0,
    "aggs": {
        "sources": {
            "terms": {
                "size": 10,
                "field": "id.url"
            }
        }
    },
    "filter": {
        "missing": {
            "field": "isResource"
        }
    }
}
```
Notice that the buckets returned are for terms like "http" (hundreds of thousands of items) and other pieces of URLs. But a URL should not be broken up like this. I believe this would be resolved by setting the mapping for the id.url field to "not_analyzed" but I am not really all that familiar with elastic search.

If there is another way of detecting duplication of this sort, please let me know.

**Comment by fabianvf** [comment]
I will take a look at this. We are in the process of doing some backend changes to our elasticsearch setup, I'll add this mapping update as soon as those are done. Nice catch, and I think changing the mapping is the correct thing to do here.

**Comment by efc** [comment]
@fabianvf, good to hear this is likely to be resolved with the backend changes. Any idea on the timeline for that (I am trying to dig into what may be a bug related to this sort of duplication and curious when I should plan to return to that task). By the way, great to have you on board more permanently!

**Comment by fabianvf** [comment]
@efc Thanks, I am excited to be back! I don't have a concrete estimate quite yet (still getting settled), but it should be resolved at worst by the end of next week. If you think it is high-priority, I can adjust that estimate.

**Comment by efc** [comment]
No, that sounds perfectly fine, @fabianvf. I was just trying to get a ballpark.

**Comment by fabianvf** [comment]
I have remapped this. We have also temporarily removed pubmed, it will be back up soon.

**Comment by efc** [comment]
great, this is working now. thanks @fabianvf
