### ISSUE TITLE
query_string failure

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#138]
Any idea why this script would fail?

```
import json
import requests

# SHARE-dev settings
OSF_APP_URL = 'https://share-dev.osf.io/api/v1/app/6qajn/?raw=True'
HEADERS = {'Content-Type': 'application/json'}

query = '''
{
    "query_string": {
        "query": "bob"
    }
}
'''
result = requests.post(OSF_APP_URL, headers=HEADERS, data=query, verify=False).json()

print json.dumps(result, indent=4)
```

It is failing for me with the following error:

```
{
    "referrer": null, 
    "code": 400, 
    "message_long": "If this should not have occurred and the issue persists, please report it to <a href=\"mailto:support@osf.io\">support@osf.io</a>.", 
    "message_short": "Bad request"
}
```

I'm not sure why this is. The GET version of this works fine:  https://share-dev.osf.io/api/v1/app/6qajn/?raw=True?q=bob results in over 200 hits.

**Comment by fabianvf** [comment]
The following should work for you. The query_string query needed a default_field attribute (I just set it to ```_all``` which will search all fields), and the entire query needed to be wrapped by a query object. Let me know if you have any more trouble.


```python
import json
import requests

# SHARE-dev settings
OSF_APP_URL = 'https://share-dev.osf.io/api/v1/app/6qajn/?raw=True'
HEADERS = {'Content-Type': 'application/json'}

query = '''
{
    "query": {
        "query_string": {
            "query": "bob",
            "default_field": "_all"
        }
    }
}
'''
result = requests.post(OSF_APP_URL, headers=HEADERS, data=query, verify=False).json()
```

**Comment by efc** [comment]
The outer "query" object was the trick. There is a built in default for the "default_field" so that is ok to leave out. I wonder why they don't show that outer object in the [elastic search docs](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html)?

Thanks for cluing me in, @fabianvf!
