### ISSUE TITLE
Links to raw records not working

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#139]
Our normalized data is supposed to have a link to the [raw record](https://github.com/CenterForOpenScience/SHARE/issues/109), but that link seems to be in a format that cannot be used outside of COS. For example, I am given this link for one of our records: http://162.242.241.121//archive/crossref/MTAuMTI3MzcvNTA3MC4xMA==/2015-01-20T00:01:57.486687/raw.xml, but this URL (and indeed every raw URL I have tried) produce only a "document is empty" error.

**Comment by fabianvf** [comment]
The link you posted seems to be a json blob saved into an xml file. This is likely an error in the arxiv consumer, I will look into it.

**Comment by efc** [comment]
Hm. That could also be an error in the tool I am using to consume this JSON output from ES. I'll dig deeper on my end too.

**Comment by efc** [comment]
Turns out my other problem was UTF-8, still getting the bad links. I am seeing this problem on the crossref consumer as well.
