### ISSUE TITLE
Missing titles?

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#140]
How we end up with [this missing title situation](http://share.clst.org/id/54bda066b5e9d73716485730)? If the provider really did not give us a title, maybe we should use "Untitled"? Not sure.

**Comment by brianjgeiger** [comment]
I recommend against that, because missing information means something that an arbitrarily chosen name. If someone did name their paper Untitled, which I can see happening for various reasons, then we have no way of knowing that's the proper name.

**Comment by JeffSpies** [comment]
+1

**Comment by efc** [comment]
@brianjgeiger, you are absolutely right.

I think I was a bit lazy in my original suggestion. Some version of that behavior might be appropriate for a given client of this data, but much better to let the data to express blank when blank is the truth, rather than a false string of "Untitled." I'll treat this as a client-side problem.
