### ISSUE TITLE
Do we have a persistent identifier for SHARE NS records?

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#141]
In working with SHARE NS records from elastic search I realized that we may not have a persistent identifier for these records. We do have an "_id" identifier which, I believe, is created by elastic search itself as it indexes each record. But if we were to wipe out and recreate the elastic search index with some variations in configuration, then I believe those "_id" numbers might come out differently.

We need some way to address and retrieve a given research release event (a SHARE NS record) directly and reliably over time. What is our strategy for this? Can it be encapsulated as an "identifier" for the record with a URI representation that would retrieve the record itself?

**Comment by chrisseto** [comment]
The `_id` field is the primary key assigned by mongo for each piece of metadata.
So regardless of how many time we decided to destroy the elasticsearch index those will stay the same.

You could also use the `id.serviceID` as those are unique to each metadata object.
