### ISSUE TITLE
Changing white lists

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#145]
I learned from bepress this month that they have changed how they treat setSpec in their OAI feeds. 

In the past bepress has only reported the single set in which an item actually resides on the OAI record. This forced bepress institutions to provide very long and granular white lists to SHARE for which sets should be included when we harvest.

Now bepress reports all the sets in the hierarchy above this holding set as well. The beauty of this is that bepress institutions can now provide a much shorter whitelist, based on their hierarchies instead of the granular holding sets. I will be asking them to provide new whitelists in the coming weeks.

The question: what do we do with these revised white lists? How should I report them to the team?

Also, for the beta: can we design the registration process so that organizations can define their white lists as part of registering as a provider? and even cooler: could we build this in such a way that they could modify their white list without our intervention as their needs and repository structure change?

**Comment by erinspace** [comment]
This will be quite easy to do, as we can just update each harvester's approved sets, and then renormalize documents in the period we have them for already. Approved sets are stored in each harvester (for example: https://github.com/fabianvf/scrapi/blob/develop/scrapi/harvesters/calpoly.py#L21), and we can renormalize as needed with new sets approved. 

Also, provider reg form asks for lists of approved sets, and will even try to auto-gerate options based on an oai pmh endpoint.
