### ISSUE TITLE
What's the current API endpoint?

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#146]
Our documentation all says that the correct API endpoint is at https://share-dev.osf.io/api/v1/app/6qajn, but it appears that current work has turned to https://osf.io/api/v1/share. Where should I be pointing my code? Should I update the docs?

**Comment by efc** [comment]
Also noticing that the new endpoint behaves in some significantly different ways from the old. I still seem to be able to pass ES queries in, but the results don't appear to be raw ES results.

**Comment by JeffSpies** [comment]
Hi, Eric, we'll likely limit support for these API endpoints temporarily. We'll clarify that in the docs.

**Comment by efc** [comment]
One thing I can't seem to do with the new API, @JeffSpies, is get to aggregated results (buckets), which makes it hard to programmatically learn how many sources there are and what they are called. There may be a way to do this, but it is not clear what that is. Please let me know how to do that when it is feasible to do so. Thanks!

**Comment by erinspace** [comment]
New API is here  - https://osf.io/api/v1/share/
Can get to raw elasticsearch results, aka buckets, with https://osf.io/api/v1/share/?raw=True
