### ISSUE TITLE
[content provider] Arizona State University

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#147]
I have just completed the provider document for the [ASU Repository](https://github.com/CenterForOpenScience/SHARE/blob/master/providers/edu.asu.md). ASU uses their own repository software, but it does have an OAI-PMH endpoint available. The repository contains material that should not be brought into the SHARE Notification Service, so it is important that we limit our harvest to only the "research" set. Details are in the provider document.

**Comment by erinspace** [comment]
Thanks for this! 

Added to scrapi in https://github.com/fabianvf/scrapi/pull/103

**Comment by erinspace** [comment]
Now live! See results at https://osf.io/share/?q=source:asu
