### ISSUE TITLE
[content provider] The Digital Archaeological Record

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#148]
I have just completed the provider document for [The Digital Archaeological Record](https://github.com/CenterForOpenScience/SHARE/blob/master/providers/org.tdar.md). The tDAR repository is available via OAI-PMH and includes only research material, so we can harvest anything there.

**Comment by erinspace** [comment]
Thank you!

Added to scrapi in https://github.com/fabianvf/scrapi/pull/103

**Comment by erinspace** [comment]
Now live! See tdar results at  https://osf.io/share/?q=source:tdar
