### ISSUE TITLE
IDs in the new API

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#150]
Exploring the new API at https://osf.io/api/v1/share has led me to a question about IDs.

It appears that the ID for a record in SHARE is stored in the ```_id``` element of a hit. However, this ID is now appears to be a direct reuse of the id.serviceID reported by the provider, without even any provision for a namespace. For example, one ID from UIUC is "oai:www.ideals.illinois.edu:2142/73115" while another from figshare is simply "1342799". 

Since SHARE no control of the serviceID, might it not include inconvenient or even dangerous characters that could compromise certain scripts? Also, without a namespace might these IDs not collide at some point?

Am I just looking at the wrong field? Is there a unique ID for these records that is generated by scrapi pr the harvesters that I'm missing?

**Comment by fabianvf** [comment]
In the new elasticsearch backend, each service provider is its own elasticsearch type. This means that when documents are inserted into the index, they are inserted into the type corresponding to the provider, and keyed (within that type) based on ```_id```, so no collisions should occur. Essentially, the primary key of each document is a concatenation of the source and serviceID.

**Comment by efc** [comment]
That's interesting.

Using the IDs as provided still has the other downside of not allowing SHARE to control the characters that are used for IDs. In the UIUC example, the "/" created problems that, in my case, could not even be resolved with "%2F". I ended up having to base64 encode this to pass along in a RESTful way. While we can be sure to deal well with our own scripts, this could expose development partners to unnecessary risks. But I would grant that the risk is small and workarounds exist.

So given the mix of type and id, that means that I cannot guarantee a unique result by just searching for the matching id, I should search for a combo of type & id (or in the terms of the ```_source``` for now, the ```source``` and ```id.serviceID```. Will that combo always get me back to the same record?
