### ISSUE TITLE
Raw URLs not accessible

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#151]
The raw URLs being shipped by the API are not retrievable from the outside world. They seem to be of the form...

http://162.242.241.121//archive/uiucideals/b2FpOnd3dy5pZGVhbHMuaWxsaW5vaXMuZWR1OjIxNDIvNzMxMTU=/2015-01-25T00:11:40.353891+00:00/raw.xml 

This uses an IP address that is not accessible.

Also, that ```//archive``` seems a bit odd. Why the double-slash?

**Comment by erinspace** [comment]
Hi @efc, this is one of the features that's being refactored along with the new cassandra storage backend. This was an artifact of when files were stored on a plain filesystem, which is no more. Raw files will be unavailable until this particular piece is reworked - coming soon!

**Comment by efc** [comment]
OK, thanks for the update, @erinspace.
