### ISSUE TITLE
Expand documentation on searchable fields

### ISSUE THREAD

**Issue by erinspace** [CenterForOpenScience/SHARE#154]
In both the example SHARE OSF search page, and on the json API.

Right now, search options documented at https://osf.io/wur56/wiki/Feed%20Options/ , but does not sufficiently connect the [metadata schema](https://osf.io/wur56/wiki/Schema/) to the elasticsearch options.

**Comment by laurenbarker** [comment]
This issue is for SHARE v1. SHARE v2 issue tracking has moved to Jira.
