### ISSUE TITLE
Look into IFTTT for additional SHARE Notifications

### ISSUE THREAD

**Issue by erinspace** [CenterForOpenScience/SHARE#157]
https://ifttt.com/

Users could use IFFTTT to configure custom searched email notifications that they'd like sent to them, configure texts, make their lights turn on, whatever they'd like to using this service.

We'd probably add SHARE as a "channel" to connect to any other channel!

**Comment by efc** [comment]
FYI, DPLA was trying to become an IFTTT channel a year ago or so. I'm not sure how this went, but we could ask them. My impression was that becoming a channel was non-trivial.

**Comment by erinspace** [comment]
Thanks @efc for the insight! I've looked into it the smallest bit, and indeed it does seem non-trivial. This is also something that might happen further into the future, but just wanted to start to document the idea.

**Comment by efc** [comment]
It is a _great_ idea. I hope it can be done.

**Comment by amandafrench** [comment]
I will say that IFTTT is basically my RSS reader these days (shameful: I feed all my feeds to email), so it is indeed a great idea. But of course IFTTT might just reply that users can use the Atom feed channel for the SHARE feed, so I think becoming a channel would indeed be difficult.

**Comment by laurenbarker** [comment]
Closing this since, as stated in the above comment, users can use the Atom feed channel for the SHARE feed.
