### ISSUE TITLE
SHARE Notify Consumer Tracking

### ISSUE THREAD

**Issue by gtananbaum** [CenterForOpenScience/SHARE#166]
SHARE should contemplate how we track consumers of the Notify feed so that if we make schema changes, etc. we can alert consumers.

**Comment by erinspace** [comment]
Agreed! 

We already have [a changlelog for SHARE](https://github.com/CenterForOpenScience/SHARE/blob/master/CHANGELOG) that we update with every major release, including schema changes.

Assuming we want to avoid any kind of log in for users to access SHARE data, we can start out with making a link to join the SHARE mailing list more prominent, and continue to make sure sure significant SHARE schema changes are mentioned there.  We can also make the changelog content a more focused part of the site. 

We can of course discuss alternate options, but those are some ways we can quickly get started informing users of changes without collecting email addressed of those actually using SHARE, which seems a bit prohibitive to promoting use.
