### ISSUE TITLE
Improve alignment of 'Sort by' drop-down menu 

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/SHARE#173]
## Steps

1. Log in to osf.io.
2. Click on search at the top of the navbar.
3. Type a topic to search.
4. On the results page, click on SHARE.
5. Once you are directed to the Share page with article results, click on ‘Sort by’ under the graph and ensure you have two options: Relevance and Date. 
7. Notice the drop-down menu.

## Expected Behavior

I expect that the drop-down menu will be aligned with the 'Sort by' button. 

## Actual Behavior

The drop-down that appears is off-centered.

## Screenshot

![share_dropdown](https://cloud.githubusercontent.com/assets/7093086/8622945/59015e4c-26fc-11e5-9812-c357f8c9bd6e.png)

**Comment by erinspace** [comment]
thanks @NatashaRichter! @fabianvf  is working with the search page at the moment, so he can probably make this change along with the others, yeah?

**Comment by NatashaRichter** [comment]
Thanks @erinspace and @fabianvf!
