### ISSUE TITLE
Improve alignment of 'Next' Button

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/SHARE#174]
From the Share page, scroll down and click on "Become a SHARE Notify Provider." Once redirected, click "Register as a Provider." Notice the "Next" button placement below.

It would look nice if the button was aligned with the fields above (shifted to the right).

![next_button](https://cloud.githubusercontent.com/assets/7093086/8624871/16b4ca62-2709-11e5-9bee-2399f2829a75.png)

**Comment by laurenbarker** [comment]
Fixed in SHARE v2. Closing.
