### ISSUE TITLE
Investigate scalar as SHARE provider

### ISSUE THREAD

**Issue by JudyRuttenberg** [CenterForOpenScience/SHARE#177]
http://scalar.usc.edu/ aggregates metadata about digital scholarship; has open API

**Comment by erinspace** [comment]
Great! Thanks @JudyRuttenberg, it's been added to the todo list :)

**Comment by laurenbarker** [comment]
This issue was completed. See [Jira](https://openscience.atlassian.net/browse/SHARE-106).
