### ISSUE TITLE
DataCite MDS as source instead of originating repository

### ISSUE THREAD

**Issue by khpope** [CenterForOpenScience/SHARE#179]
Hello. I've noticed that some events listed in SHARE that originated from Columbia University's Academic Commons show up with the source DataCite MDS. We use DataCite DOIs, so it follows that our content would appear in the MDS. However, this presents a basic problem--when I filter on Columbia Academic Commons in the SHARE search results, I won't see all events originating from our repository. Some of these events will only show up if DataCite MDS is a filter as well. I am not sure if there is a pattern involved in which events are designated as Columbia Academic Commons vs. DataCite MDS. 

Though I understand how this could be happening, it does make me wonder how I would advise a research administrator, for example, to set up a trustworthy feed from SHARE Notify. Searching on researcher or institutional names produces mixed results.

**Comment by laurenbarker** [comment]
Hi @khpope, I apologize for the delayed response; I hope your inquiry has already been addressed in a different forum. There are a few ways to narrow down search results in SHARE. To get a more complete picture of the research coming from Columbia Academic Commons everything from your source should be considered:
- Columbia Academic Commons as the source
- DataCite MDS set specs specific to Columbia Academic Commons which we list under tags (culis or cdl.culis)
- Academic Commons, Columbia University as the publisher

The below query will autofill in the search box on the SHARE Discover page by going to this [link](https://share.osf.io/discover?q=publishers%3A%22Academic%20Commons%2C%20Columbia%20University%22%20OR%20sources%3A%22Columbia%20Academic%20Commons%22%20OR%20(sources%3A%22DataCite%20MDS%22%20AND%20tags%3A(%22cdl.culis%22%20OR%20%22culis%22))):
`publishers:"Academic Commons, Columbia University" OR sources:"Columbia Academic Commons" OR (sources:"DataCite MDS" AND tags:("cdl.culis" OR "culis"))` 

As can be seen in the screenshot below, there is an option to "View query body". This exposes the url and request body that can be used to set up a feed for the current query. 

![screen shot 2017-04-26 at 10 14 45 am](https://cloud.githubusercontent.com/assets/7131985/25439312/1ee77eee-2a6a-11e7-81f8-1f9adca347e7.png)

Please don't hesitate to follow up if you have more questions!

**Comment by laurenbarker** [comment]
I'm going to go ahead and close this ticket. Feel free to reopen or create a new one if you have more questions.
