### ISSUE TITLE
Please investigate PubAg-NAL USDA as a provider

### ISSUE THREAD

**Issue by JudyRuttenberg** [CenterForOpenScience/SHARE#180]
http://pubag.nal.usda.gov/pubag/home.xhtml

**Comment by GaryKriebel** [comment]
Thanks, Judy.

I've added the request to our harvester backlog.

**Comment by laurenbarker** [comment]
The analysis was completed. More info on [Jira](https://openscience.atlassian.net/browse/SHARE-244).
