### ISSUE TITLE
Incorrect contact info for IDEALS at UIUC

### ISSUE THREAD

**Issue by asteino** [CenterForOpenScience/SHARE#181]
Hello,

This issue is for IDEALS SHARE provider documentation, located here: https://github.com/CenterForOpenScience/SHARE/blob/master/providers/edu.illinois.ideals.md 
Sarah Shreeves is no longer at the University of Illinois. Please update the contact information to be the IDEALS Team: ideals-gen [at] illinois [dot] edu.

Thanks!

Ayla

**Comment by GaryKriebel** [comment]
Thanks, Ayla.  You can see that I've created a request to update the information.

**Comment by laurenbarker** [comment]
This issue has been resolved.
