### ISSUE TITLE
Eagle-i

### ISSUE THREAD

**Issue by JeffSpies** [CenterForOpenScience/SHARE#183]
Provider?

https://www.eagle-i.net/

Follow-up with

https://twitter.com/jenlrile/status/685824494523531265

when complete.

**Comment by erinspace** [comment]
@JeffSpies [Jira ticket](https://openscience.atlassian.net/browse/SHARE-256) has been in the harvester backlog for a few days, moved it  to the sprint and added the tweet to the ticket so we follow up!

**Comment by JeffSpies** [comment]
Excellent, thanks!

**Comment by laurenbarker** [comment]
This analysis was completed in SHARE v1 and was addressed on Jira. Closing.
