### ISSUE TITLE
[content provider] DMPTool

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#22]
I just added [provider documentation for DMPTool](https://github.com/CenterForOpenScience/SHARE/blob/master/providers/org.cdlib.dmp.md) to the project. Public data management plans from roughly 800 sites can be shared from DMPTool to give consumers of the SHARE Notification Service early notice of new research and grant awards.

Patricia Cruse plans on sending along a pointer to the DMPTool API, I'll update the documentation when I get that. For now it includes the answers to our metadata sharing questions which were cleared today (7/22/2014).

**Comment by laurenbarker** [comment]
Going to close this issue since it hasn't been updated since 2014.
