### ISSUE TITLE
[normalizer] Update BioMed Central Normalizer with Extra Data 

### ISSUE THREAD

**Issue by caseyrollins** [CenterForOpenScience/SHARE#251]
The BioMed Central normalizer should have an ```Extra``` class within ```CreativeWork``` for some of the data that is not currently being normalized. The fields currently being ignored are noted in ```otherProperties``` in the BioMed Central scehma [here](https://github.com/CenterForOpenScience/scrapi/blob/develop/scrapi/harvesters/biomedcentral.py).

**Comment by SSJohns** [comment]
I'll try and workon getting this up and running.

**Comment by SSJohns** [comment]
Hey this is solved with this pull request. 
#217
