### ISSUE TITLE
[normalizer] Parse More Link Types in the OAI Normalizer (ISBN, etc.)

### ISSUE THREAD

**Issue by caseyrollins** [CenterForOpenScience/SHARE#261]
Currently, the only allowed link types are ```'doi'```, ```'provider'```, and ```'misc'```.

**Comment by SSJohns** [comment]
Looking into this one.

**Comment by SSJohns** [comment]
I'm putting this back.

**Comment by aaxelb** [comment]
Moved to https://openscience.atlassian.net/browse/SHARE-397
