### ISSUE TITLE
Update the Atom feed to use new SHARE API

### ISSUE THREAD

**Issue by erinspace** [CenterForOpenScience/SHARE#273]
The old SHARE Atom feed is in use by many libraries:

https://osf.io/share/atom/?jsonQuery=%257B%2522query%2522%253A%257B%2522match_all%2522%253A%257B%257D%257D%252C%2522from%2522%253A-10%257D

It works by passing a json query to an API endoint that formats as Atom. 

https://github.com/CenterForOpenScience/osf.io/blob/develop/website/search/share_search.py#L311

**Comment by laurenbarker** [comment]
Closing since the atom feed is in production. https://share.osf.io/api/v2/atom/?elasticQuery=%7B%22query_string%22%3A%7B%22query%22%3A%22*%22%7D%7D

**Comment by hmoco** [comment]
Nooooooooooooo I was so close to finishing thiiissss

**Comment by hmoco** [comment]
Just kidding, nice feature
