### ISSUE TITLE
possible integrator: scirate - requires follow-up discussion perhaps

### ISSUE THREAD

**Issue by silky** [CenterForOpenScience/SHARE#3]
i was just talking to andrew sallans and he commented that the 'scirate' website - https://scirate.com/ - may like to integrate with this, supposing it existed and had was able to provide content in a timely fashion, etc, etc.

i've suggested this idea to scirate here - https://github.com/draftable/scirate3/issues/268

(i've created this as an "issue" even though it's maybe not actionable, so feel free to delete or move to somewhere more appropriate; perhaps the wiki.)

**Comment by laurenbarker** [comment]
Going to close this ticket as the related ticket has been closed.
