### ISSUE TITLE
Fix 404s on the ADMIN interface

### ISSUE THREAD

**Issue by chrisseto** [CenterForOpenScience/SHARE#312]
![screen shot 2016-07-21 at 15 04 23](https://cloud.githubusercontent.com/assets/5532905/17035286/77a26590-4f54-11e6-9c46-9efe142caafe.png)

**Comment by SSJohns** [comment]
I think this might be my fault. Hold on.

**Comment by SSJohns** [comment]
Yeah it seems like collect static is no longer pulling the files from project/static

**Comment by SSJohns** [comment]
Oh I solved it. Is it supposed to be name hotfix?

**Comment by chrisseto** [comment]
Nope, still a feature. Master has nothing in it right now.

On Thu, Jul 21, 2016 at 3:29 PM, Shaquille Johnson <notifications@github.com

**Comment by SSJohns** [comment]
Cool, it's done. That should fix it.

**Comment by chrisseto** [comment]
Thanks!
