### ISSUE TITLE
Add a notice to the existing SHARE page

### ISSUE THREAD

**Issue by chrisseto** [CenterForOpenScience/SHARE#338]
We should add a status update on the existing search page detailing that v2 is on the way out and v1 will no longer be receiving updates.

**Comment by rickjohnson** [comment]
How about something like this...

"We are excited to share that we are nearing completion of an update to SHARE's data and related discovery pages.  As a result, only minor updates will be applied to version 1 (v1) of SHARE over the next few weeks while v2 is being prepared for release.  More to come soon!"

**Comment by chrisseto** [comment]
Thanks @rickjohnson!
