### ISSUE TITLE
Handle garbage records

### ISSUE THREAD

**Issue by leb2dg** [CenterForOpenScience/SHARE#350]
Decide how to deal with this stuff: https://staging-share.osf.io/curate/creativework/7156954

Maybe a "Mark as garbage" button on curate page.

**Comment by SSJohns** [comment]
Flag as spam, and notifies who?

**Comment by SSJohns** [comment]
Or a report button.

**Comment by aaxelb** [comment]
Moved to https://openscience.atlassian.net/browse/SHARE-387
