### ISSUE TITLE
JSON Schema endpoint

### ISSUE THREAD

**Issue by aaxelb** [CenterForOpenScience/SHARE#366]
endpoint that returns the schema built by JSONLDValidator

**Comment by chrisseto** [comment]
Should ideally have an endpoint for the entire graph and sub-endpoints for individual types.
Maybe links?

Side note: Adding [django descriptions](https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.Field.description), if available, to the schema would be very helpful

`.../schema/`
`.../schema/tag`
`.../schema/person`
