### ISSUE TITLE
On share.osf.io opening link with 'undefined' has missing contributors

### ISSUE THREAD

**Issue by rickjohnson** [CenterForOpenScience/SHARE#402]
When going to share.osf.io and then clicking the magnifying glass without entering any text

![screen shot 2016-08-29 at 2 10 42 pm](https://cloud.githubusercontent.com/assets/296657/18063580/93e0483a-6df9-11e6-8330-4db9aeedce01.png)

It brings you to a screen with only half data providers.

![screen shot 2016-08-29 at 2 10 35 pm](https://cloud.githubusercontent.com/assets/296657/18063598/a7db1130-6df9-11e6-8a60-59f878e1fd13.png)

When you remove the word 'undefined' more are represented

![screen shot 2016-08-29 at 2 10 35 pm](https://cloud.githubusercontent.com/assets/296657/18063605/b658b9ec-6df9-11e6-94e1-0e94d73fcfc5.png)

**Comment by leb2dg** [comment]
Issue moved to [CenterForOpenScience/ember-share #91](https://github.com/CenterForOpenScience/ember-share/issues/91) via [**ZenHub**](https://www.zenhub.com/)
