### ISSUE TITLE
Link Related Works in SHARE

### ISSUE THREAD

**Issue by rickjohnson** [CenterForOpenScience/SHARE#404]
The SHARE data model current supports linking different related entities (e.g. researcher to institution, researcher to publication, etc).  However, linking items of the same entity type is not supported yet (esp. dataset to publication, dmp to dataset, dmp to osf project).  Any abstractcreativework should be able to be linked to another abstractcreativework.  While I assume these links will be mapped via the RDBMS schema, they would ideally implement the patterns in RMAP for asserting relationships:  http://rmap-project.info/rmap/wp-content/uploads/JCDL2015_Poster_HandoutSize.pdf (see labels on arrows under "How it Works")

https://osf.io/j34su/.  (see slide 2 of that presentation showing the relationship patterns).  SHARE supports all of this now EXCEPT the work to work assertions.)

Changes such as the following are likely needed:
- Add join table for two related works that includes two abstractcreativework ids and field for relationship type (maybe using RMAP Disco: http://rmap-project.info/rmap/wp-content/uploads/JCDL2015_Poster_HandoutSize.pdf).  Also, ideally it uses the URI value for the relationship.  Will see if I can track that down.
- Likely changes to harvester, push API, and curation tools to assert these relationships
- Likely changes to ember-share app to filter on relationships (i.e. new filter tag on left sidebar)
- Opportunities for visualizing relationships of objects in a graph

**Comment by rickjohnson** [comment]
I assume this should have label 'Epic', but I do not see how to add that label (I may not have permission)

**Comment by rickjohnson** [comment]
Here is link to more info about RMAP:

https://rmap-project.atlassian.net/wiki/display/RMAPPS/Data+Model

**Comment by rickjohnson** [comment]
Thinking more table could just mirror subject object predicate where subject and object are primary keys for objects in abstractcreativework and predicate is a machine addressable URI within a community ontology

This may be most comprehensive ontology to use first:

http://www.sparontologies.net/ontologies/cito/source.html#d4e101

Under object properties examples include:

uses_data_from, uses_method_in, describes, retracts, cites, derides, is_refuted_by

So example row could be
subject object predicate
12356   45678 uses_data_from

Where 12356 is an article and 45678 is a dataset (in a sentence would be: article 12356 uses data from dataset 45678)

**Comment by laurenbarker** [comment]
Closing since SHARE supports work to work relations now.
