### ISSUE TITLE
Link Derivative Works Together

### ISSUE THREAD

**Issue by rickjohnson** [CenterForOpenScience/SHARE#406]
Potentially utilizing the same mechanism (e.g. table) in #404 (Link related works), be able to link different versions of objects (e.g. forks, derivatives, newer versions of datasets)

**Comment by laurenbarker** [comment]
SHARE also supports work relations which can be found https://github.com/CenterForOpenScience/SHARE/blob/develop/share/models/relations/creative.yaml. Commented out relation types are ones that aren't used in any metadata we harvest.
