### ISSUE TITLE
Add Digital Conservancy harvester

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/SHARE#434]
Base url:
http://conservancy.umn.edu/oai/request/

Description:
The Digital Conservancy is the institutional repository of the University of Minnesota, which provides free, public access and long-term preservation to work created at the U of M. As such, the University of Minnesota Digital Conservancy (UDC) is a a venue for faculty to deposit open access copies of their scholarly work; a showcase for select student works, such as dissertations and honors theses; home to the Data Repository for the University of Minnesota (DRUM); and centralized, searchable access point to institutional digital records including those of the University of Minnesota Archives.

Oai provider?
Yes

Provider long name:
University of Minnesota, Digital Conservancy

Rate limit:
We have no time interval restrictions.

Approved sets:
[u'<setSpec>com_11299_45272</setSpec>,<setSpec>com_11299_169792</setSpec>,<setSpec>com_11299_166578</setSpec>']

Per request rate limit:
0

JIRA link: https://openscience.atlassian.net/browse/SHARE-290

**Comment by zamattiac** [comment]
This provider already exists as edu.udc. Is there a change that needs to be made?
