### ISSUE TITLE
Add harvester for Mendeley

### ISSUE THREAD

**Issue by leb2dg** [CenterForOpenScience/SHARE#450]
Api docs:
https://api.mendeley.com/apidocs/docs

Base url:
https://data.mendeley.com

Description:
Mendeley Data is an open research data repository, which enables researchers to publish their research data, receive a DOI and be cited, and to discover, access and reuse data.

Provider long name:
Mendeley Data

Rate limit:
1 request/minute

Property list:
None

**Comment by HarvAce** [comment]
We're working on this one! :)
