### ISSUE TITLE
Add harvester for Universidad del Rosario

### ISSUE THREAD

**Issue by leb2dg** [CenterForOpenScience/SHARE#453]
Base url:
http://repository.urosario.edu.co/oai/request

Description:
We are an academic institution that promotes the open access to the institutional production in academy and research.

Oai provider?
Yes

Provider long name:
Universidad del Rosario

Property list:
['publisher', 'language', 'format', 'rights', 'source', 'relation', 'date', 'identifier', 'type']

Approved sets:
[u'com_10336_3', u'com_10336_3097', u'col_10336_683', u'com_10336_2450', u'col_10336_2442', u'com_10336_12021', u'col_10336_2975', u'col_10336_199', u'com_10336_3178', u'com_10336_566', u'com_10336_952', u'com_10336_564', u'com_10336_885', u'com_10336_569', u'com_10336_925', u'col_10336_1308', u'col_10336_1273', u'col_10336_1274', u'col_10336_1544', u'col_10336_993', u'col_10336_2706', u'col_10336_1557', u'col_10336_1290', u'col_10336_926', u'col_10336_2564', u'col_10336_2082', u'col_10336_965', u'col_10336_1658', u'col_10336_1357', u'col_10336_1547', u'col_10336_1545', u'col_10336_1546', u'col_10336_886', u'col_10336_1282', u'col_10336_1552', u'col_10336_1266', u'col_10336_1285', u'col_10336_2694', u'col_10336_1574', u'col_10336_1306', u'col_10336_1553', u'col_10336_1267', u'col_10336_1967', u'col_10336_1556', u'col_10336_1555', u'col_10336_1349', u'col_10336_1600', u'col_10336_1284', u'col_10336_1183', u'col_10336_1554', u'col_10336_2655', u'col_10336_1622', u'col_10336_2451', u'col_10336_1551', u'com_10336_565', u'com_10336_2775', u'com_10336_11682', u'com_10336_567', u'com_10336_4996', u'com_10336_568', u'com_10336_834', u'com_10336_966', u'com_10336_12018', u'col_10336_2254', u'com_10336_563', u'col_10336_165', u'col_10336_1548', u'col_10336_967', u'col_10336_953', u'col_10336_835', u'col_10336_2776', u'col_10336_1659', u'col_10336_1623', u'col_10336_1182', u'col_10336_2149', u'col_10336_164', u'col_10336_729', u'col_10336_2179', u'col_10336_574', u'col_10336_752', u'col_10336_1924', u'col_10336_576', u'col_10336_622', u'col_10336_1421', u'col_10336_582', u'col_10336_583', u'col_10336_1730', u'col_10336_2081', u'col_10336_2258', u'col_10336_621', u'col_10336_946', u'col_10336_601', u'col_10336_867', u'col_10336_1475', u'com_10336_4', u'com_10336_6343', u'com_10336_5674', u'com_10336_562', u'com_10336_561', u'com_10336_10783']

Per request rate limit:
0

**Comment by huangjenny** [comment]
I'm working on this @ GHC '16

**Comment by leb2dg** [comment]
@huangjenny, did you get a chance to submit a PR for Universidad del Rosario one or was it not finished?

**Comment by huangjenny** [comment]
@leb2dg It's not finished. I had errors trying to do a PR.

**Comment by leb2dg** [comment]
Okay, thanks for letting me know! Glad you participated in OSD :) If you are still interested in making the PR I can walk you through the steps.
