### ISSUE TITLE
Add Harvester for Boston University

### ISSUE THREAD

**Issue by caseyrollins** [CenterForOpenScience/SHARE#460]
Base url:
https://na03.alma.exlibrisgroup.com/view/oai/01BOSU_INST/request

Description:
Boston University is an international, comprehensive, private research university, committed to educating students to be reflective, resourceful individuals ready to live, adapt, and lead in an interconnected world. Boston University is committed to generating new knowledge to benefit society.

OAI Provider?
Yes

Provider long name:
Boston University

Approved sets:
[u'bu_theses']

Per request rate limit:
0

**Comment by HarvAce** [comment]
https://na03.alma.exlibrisgroup.com/view/oai/01BOSU_INST/request?verb=ListRecords&metadataPrefix=oai_dc&set=bu_theses

Does not return any data.  Please ensure data available.
