### ISSUE TITLE
Add Harvester for Texas Tech

### ISSUE THREAD

**Issue by caseyrollins** [CenterForOpenScience/SHARE#461]
Base url:
https://ttu-ir.tdl.org/ttu-oai/request

Description:
The Texas Tech University Libraries is the center of academic, social and intellectual discovery on the Texas Tech University campus. Texas Tech University is a public university located in Lubbock, TX.

OAI Provider?
Yes

Provider long name:
Texas Tech University Libraries

Property list:
['language', 'format', 'rights', 'date', 'identifier', 'type']

Approved sets:
[u'col_2346_521', u'col_2346_469']

Per request rate limit:
0

**Comment by HarvAce** [comment]
We're working on this one #GHC2016 :)
