### ISSUE TITLE
Add Harvester for University of Maryland Libraries

### ISSUE THREAD

**Issue by leb2dg** [CenterForOpenScience/SHARE#471]
OAI Provider:
Yes

Base URL:
http://drum.lib.umd.edu/oai/request

Source name:
University of Maryland Libraries

Description:
The University of Maryland Libraries maintains DRUM (Digital Repository at the University of Maryland) available at http://drum.lib.umd.edu/. DRUM collects, preserves, and provides public access to the scholarly output of the university.

Properties list: 
['date', 'relation', 'identifier', 'type', 'language']

Approved sets: 
[u'com_1903_1654', u'com_1903_2205', u'com_1903_2206', u'com_1903_2207', u'com_1903_2208', u'com_1903_2209', u'com_1903_2210', u'com_1903_2211', u'com_1903_10990', u'com_1903_2212', u'com_1903_2213', u'com_1903_2214', u'com_1903_2215', u'com_1903_2264', u'com_1903_2271', u'com_1903_11810', u'com_1903_11811', u'com_1903_11609', u'com_1903_7565', u'com_1903_2219', u'com_1903_11812', u'com_1903_2221', u'com_1903_2222', u'com_1903_1598', u'com_1903_1611', u'com_1903_8', u'com_1903_12', u'com_1903_1647', u'com_1903_1631', u'com_1903_2223', u'com_1903_2224', u'com_1903_2225', u'com_1903_7097', u'com_1903_2227', u'com_1903_2230', u'com_1903_2231', u'com_1903_2232', u'com_1903_2234', u'com_1903_2235', u'com_1903_11813', u'com_1903_2237', u'com_1903_2238', u'com_1903_2216', u'com_1903_7125', u'com_1903_2239', u'com_1903_2240', u'com_1903_2241', u'com_1903_6626', u'com_1903_12164', u'com_1903_9069', u'com_1903_2242', u'com_1903_2243', u'com_1903_2244', u'com_1903_7124', u'com_1903_2245', u'com_1903_2246', u'com_1903_2247', u'com_1903_2262', u'com_1903_2249', u'com_1903_4375', u'com_1903_2250', u'com_1903_2251', u'com_1903_2252', u'com_1903_2253', u'com_1903_2254', u'com_1903_11321', u'com_1903_2278', u'com_1903_2255', u'com_1903_2256', u'com_1903_2257', u'com_1903_2258', u'com_1903_2259', u'com_1903_10067', u'com_1903_2260', u'com_1903_2261', u'com_1903_10091', u'com_1903_2263', u'com_1903_2265', u'com_1903_2267', u'com_1903_1629', u'com_1903_2268', u'com_1903_2269', u'com_1903_2266', u'com_1903_10116', u'com_1903_2270', u'com_1903_2272', u'com_1903_8706', u'com_1903_1584', u'com_1903_1607', u'com_1903_1633', u'com_1903_1618', u'com_1903_2273', u'com_1903_2233', u'com_1903_5', u'com_1903_2229', u'com_1903_2276', u'com_1903_2277', u'com_1903_10', u'com_1903_2279', u'com_1903_2280']

**Comment by cmaimone** [comment]
Christina working on it

**Comment by leb2dg** [comment]
@cmaimone, did you get a chance to submit a PR for University of Maryland or was it not finished?

**Comment by cmaimone** [comment]
Ok - I tried making a pull request, but I have no idea if I did it
correctly (the harvester is correct, I'm just not confident about the pull
request procedure).

Christina

**Comment by cmaimone** [comment]
It's finished but I haven't made a pull request yet. I'll try to tomorrow

Christina

**Comment by leb2dg** [comment]
@cmaimone, you submitted the PR ( #489  ) properly 👍  I just moved the commits around a little so they are now in #488 and #490. Your changes will be merged via those PRs, thank you!
