### ISSUE TITLE
Add Harvester for University of Richmond

### ISSUE THREAD

**Issue by leb2dg** [CenterForOpenScience/SHARE#473]
Base url:
http://scholarship.richmond.edu/do/oai/

Description:
The University of Richmond is a private, nonsectarian, liberal arts college located in the city of Richmond, Virginia. The University of Richmond is a primarily undergraduate, residential university with approximately 4,350 undergraduate and graduate students in five schools: the School of Arts and Sciences, the E. Claiborne Robins School of Business, the Jepson School of Leadership Studies, the University of Richmond School of Law and the School of Professional & Continuing Studies.

Provider long name:
Boatwright Memorial Library, University of Richmond

Property list:
None

Per request rate limit:
0

**Comment by aishanibhalla** [comment]
Working on it
