### ISSUE TITLE
Add Harvester for University of Arkansas

### ISSUE THREAD

**Issue by leb2dg** [CenterForOpenScience/SHARE#474]
Source name:
ScholarWorks@UARK

OAI source:
Yes

Base URL:
http://scholarworks.uark.edu/do/oai/

Source documentation:
http://uark.libguides.com/c.php?g=536547

Properties list:
['publisher', 'format', 'source', 'date', 'identifier', 'type']

Description:
ScholarWorks@UARK, a Digital Commons Repository, highlights a growing collection of faculty publications, presentations, student work and teaching materials. The University of Arkansas is committed to disseminating its research and scholarship as widely as possible.

Approved Sets:
[u'acct', u'acctetd', u'acctuht', u'aeab', u'aeabetd', u'aeabuht', u'aect', u'aectetd', u'aectuht', u'ansc', u'anscpub', u'anscetd', u'anscuht', u'anrlaw', u'anth', u'anthetd', u'anthuht', u'ampd', u'ampduht', u'arch', u'archuht', u'arts', u'artsetd', u'artsuht', u'arscdeanuht', u'bisc', u'biscpub', u'biscetd', u'biscuht', u'baeg', u'baegpub', u'baegetd', u'baeguht', u'bmeg', u'bmegetd', u'bmeguht', u'cast', u'cheg', u'chegpub', u'chegetd', u'cheguht', u'chbc', u'chbcpub', u'chbcetd', u'chbcuht', u'cveg', u'cvegpub', u'cvegetd', u'cveguht', u'coehp', u'engr', u'depts', u'comm', u'commetd', u'commuht', u'csce', u'cscepub', u'csceetd', u'csceuht', u'cses', u'csespub', u'csesetd', u'csesuht', u'cied', u'ciedetd', u'cieduht', u'afls', u'econ', u'econetd', u'econuht', u'edre', u'edreetd', u'edreuht', u'eleg', u'elegpub', u'elegetd', u'eleguht', u'engl', u'engletd', u'engluht', u'ento', u'entopub', u'entoetd', u'entouht', u'fjsa', u'finn', u'finnetd', u'finnuht', u'fdsc', u'fdscpub', u'fdscetd', u'fdscuht', u'ghes', u'ghesetd', u'ghesuht', u'geos', u'geosetd', u'geosuht', u'hhpr', u'hhpretd', u'hhpruht', u'hist', u'histetd', u'histuht', u'hnrc', u'hnrcpub', u'hort', u'hortpub', u'hortetd', u'hortuht', u'hdfsrs', u'hdfsrsuht', u'hnhi', u'hnhiuht', u'ineg', u'inegpub', u'inegetd', u'ineguht', u'isys', u'isysetd', u'isysuht', u'ides', u'idesuht', u'arsc', u'arscdean', u'jour', u'jouretd', u'jouruht', u'larc', u'larcuht', u'mgmt', u'mgmtetd', u'mgmtuht', u'mktg', u'mktgetd', u'mktguht', u'masc', u'mascetd', u'mascuht', u'meeg', u'meegpub', u'meegetd', u'meeguht', u'musc', u'muscetd', u'muscuht', u'pat', u'phil', u'philetd', u'philuht', u'phys', u'physpub', u'physetd', u'physuht', u'plpa', u'plpapub', u'plpaetd', u'plpauht', u'plsc', u'plscetd', u'plscuht', u'posc', u'poscpub', u'poscetd', u'poscuht', u'psyc', u'psycetd', u'psycuht', u'castpub', u'rhrc', u'rhrcpub', u'rhrcetd', u'rhrcuht', u'wcob', u'hesc', u'law', u'lawpub', u'scwk', u'scwketd', u'scwkuht', u'soci', u'societd', u'sociuht', u'scmt', u'scmtuht', u'nurs', u'nursetd', u'nursuht', u'thtr', u'thtretd', u'thtruht', u'etd', u'uht', u'lib', u'libpub', u'scmtwscp', u'wllc', u'wllcetd', u'wllcuht']

**Comment by HarvAce** [comment]
We'll take this one. #GHC2016 :)
