### ISSUE TITLE
Add Harvester for Rice University Digital Scholarship Archive

### ISSUE THREAD

**Issue by leb2dg** [CenterForOpenScience/SHARE#478]
Source name:
Rice University Digital Scholarship Archive

Base URL:
https://scholarship.rice.edu/dspace-oai/request

Documentation:
https://scholarship.rice.edu/dspace-oai/

OAI source:
Yes

Preferred metadata prefix:
oai_dc

Source description:
This is Rice's institutional repository, a web site where the university's intellectual output is shared, managed, searched, and preserved. Most materials come from Rice faculty members' research, electronic theses and dissertations, and digitized collections of rare or unique books, images, musical performances, and manuscripts. The archive runs on DSpace, an open source software package.

**Comment by HarvAce** [comment]
This RICE API URL does not work - error illegal verb.  Please update base request URL.
