### ISSUE TITLE
Harvesters

### ISSUE THREAD

**Issue by chrisseto** [CenterForOpenScience/SHARE#510]
# List of harvest that need to be completed

- [x] [SHARE-297](https://openscience.atlassian.net/browse/SHARE-297) Harvester for Western University
- [ ] [SHARE-343](https://openscience.atlassian.net/browse/SHARE-343) Harvester for Project MUSE (Johns Hopkins University Press)
- [ ] [SHARE-320](https://openscience.atlassian.net/browse/SHARE-320) Harvester for Repositorio Institucional EdocUR
- [ ] [SHARE-245](https://openscience.atlassian.net/browse/SHARE-245) Harvester for BWH Division of Sleep and Circadian Disorders
- [ ] [SHARE-321](https://openscience.atlassian.net/browse/SHARE-321) Harvester for University of Kansas
- [ ] [SHARE-322](https://openscience.atlassian.net/browse/SHARE-322) Harvester for Stellenbosch University
- [ ] [SHARE-323](https://openscience.atlassian.net/browse/SHARE-323) Harvester for Augusta University
- [x] [SHARE-324](https://openscience.atlassian.net/browse/SHARE-324) Harvester for University of Utah
- [x] [SHARE-331](https://openscience.atlassian.net/browse/SHARE-331) Harvester for James Madison University
- [ ] [SHARE-332](https://openscience.atlassian.net/browse/SHARE-332) Harvester for BYU
- [ ] [SHARE-336](https://openscience.atlassian.net/browse/SHARE-336) Harvester for Telemark University College
- [ ] [SHARE-338](https://openscience.atlassian.net/browse/SHARE-338) Harvester for Cyprus University of Technology
- [ ] [SHARE-345](https://openscience.atlassian.net/browse/SHARE-345) Harvester for Northwestern University
- [ ] [SHARE-265](https://openscience.atlassian.net/browse/SHARE-265) Evaluate DTIC harvester
- [ ] [SHARE-20](https://openscience.atlassian.net/browse/SHARE-20) Add datafirst harvester
- [ ] [SHARE-348](https://openscience.atlassian.net/browse/SHARE-348) Harvester for IDEAS-RePEc
- [ ] [SHARE-349](https://openscience.atlassian.net/browse/SHARE-349) Evaluate Loop harvester
- [ ] [SHARE-371](https://openscience.atlassian.net/browse/SHARE-371) Add Science Direct harvester
- [ ] [SHARE-373](https://openscience.atlassian.net/browse/SHARE-373) Add SciencePaper online harvester
- [ ] [SHARE-430](https://openscience.atlassian.net/browse/SHARE-430) Add Harvester for University of Arkansas
- [ ] [SHARE-432](https://openscience.atlassian.net/browse/SHARE-432) Add Harvester for Digital Commons @ Luther Seminary
- [ ] [SHARE-434](https://openscience.atlassian.net/browse/SHARE-434) Add Harvester for Rice University Digital Scholarship Archive

**Comment by laurenbarker** [comment]
Closing since we keep track of these issues on JIRA.
