### ISSUE TITLE
Reporting of resources from publishers

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#58]
A researcher is publishing an article with a CHORUS-enabled publisher. When CHORUS issues notification of publication, SHARE gets a copy via CrossRef. SHARE stores metadata related to this event (such as the source, the date of release, the researcher's ORCID, funding agency, grant ID, and the DOI of the publication at its publisher) in the notification service event digest.

**Layers Involved**
- Notification Service

**Challenges**
- Details of SHARE event metadata have yet to be determined. Grant ID is particularly troublesome and may not be possible for years to come.

**Potential Requirements**
- Harvesting reports via CrossRef API.

**Notes**
What about publishers that do not participate in CrossRef? Does each need a use case or do we handle them similarly to CrossRef, supporting one-off API's for harvesting from each?

**Comment by erinspace** [comment]
Moving out of issues - For more info and commenting, please see use case google doc - https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit
