### ISSUE TITLE
Reporting of resources from local repository

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#59]
A researcher submits unpublished work to their local SHARE-enabled institutional repository. The repository collects ORCID, funder, and grant number associated with the work. Repository sends report of the submission with a Handle to the SHARE notification service. SHARE stores the event in its digest. 

**Layers Involved**
- Notification Service

**Challenges**
- Many repositories are unable to distinguish research-related material from cultural heritage material.
- Identifiers like ORCID and FundRef are generally not collected by local repositories.

**Potential Requirements**
- Repository able to provide Handle or other persistent identifier for resources.
- SHARE push API to accept push reports from repository.
- OAI-PMH harvesting tool to gather reports from repository.
- ResourceSync harvesting tool to gather reports from repository.

**Comment by erinspace** [comment]
Moving out of issues - For more info and commenting, please see use case google doc - https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit
