### ISSUE TITLE
Notification of events bounded by institution via email

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#60]
Staff at the university office of sponsored research want to be alerted to any new publication or data set arising from researchers at the university. They visit the SHARE dashboard and set up an email alert so that SHARE emails them a copy of the metadata for any new event which appears to be affiliated with the university.

Manager of an institutional repository set up email alerts so that SHARE emails the a copy of metadata for new events which appear to be affiliated with their institution.

**Layers Involved**
- Notification Service, Registry

**Challenges**
- Arbitrary stored searches could become unwieldy. Certain pre-defined channels, like institutions, may need to be defined.
- Affiliations with institutions may be difficult to determine. Email addresses of authors, or affiliations listed in author ORCID profiles may help make the connection.
-ISNI may help identify organizations, but rarely included in metadata.

**Potential Requirements**
- Widespread adoption of ORCID or consistent capture of email addresses.

**Comment by erinspace** [comment]
For more information and comment, please see the use case google doc - https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit
