### ISSUE TITLE
Notification of events bounded by funder via feed

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#61]
A funding agency manages a system that registers all new work arising from projects funded by the agency. In order to learn about resources not reported directly to them by principal investigators and project staff, they arrange for a feed of SHARE notifications relating to their agency. These notifications are integrated into their registry so that appropriate references can by copied from SHARE with little additional effort.

**Layers Involved**
- Notification Service, Registry

**Challenges**
- Arbitrary stored searches could become unwieldy. Certain pre-defined channels, like funding agencies, may need to be defined.

**Potential Requirements**
- Widespread adoption of FundRef.
- Notification API to provide feeds to consumers.
- Use of Uber Research data to help identify grants.

**Notes**
While it is easy to conceptualize this as SHARE "pushing" notifications to the agency system, it may actually be implemented more like RSS, with the agency system regularly polling SHARE for new notifications.

**Comment by erinspace** [comment]
Moving out of issues - For more info and commenting, please see use case google doc - https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit
