### ISSUE TITLE
Searching for resources related to author

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#62]
*[NOTE: This is not a Notification Service use case.]*

An administrative assistant is looking for all publications by faculty member in past year in order to complete a faculty dossier for the year. The assistant visits the SHARE dashboard, provides the faculty member's ORCID and bounds the search by the previous calendar year. SHARE provides list of resources from its registry with an option to export the list in CSV form.

**Layers Involved**
- Registry, Discovery

**Challenges**
- Unclear what formats for export would be most helpful.
- Variety of resource types in registry may make uniform export of metadata difficult.

**Potential Requirements**
- Widespread adoption of ORCID would make author identification more feasible.

**Comment by erinspace** [comment]
Moving out of issues - For more info and commenting, please see use case google doc - https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit
