### ISSUE TITLE
Monitoring resources related to funder

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#63]
[NOTE: This is not a Notification Service use case.]

A grant administrator compiling the outcomes of a grant visits the SHARE dashboard and looks up their FundRef identifier. SHARE produces a list of the most recent resources reported that related to that funder. The administrator further limits the results to a set of researchers identified by ORCID who participate in the grant project. From this list the administrator finds three resources that are outcomes of the grant but had not yet been reported through university channels.

**Layers Involved**
- Registry, Discovery

**Challenges**
- Many sources may not report ORCID or FundRef identifiers.
- What dates indicate recency? Date of publication? Date of report to SHARE?

**Potential Requirements**
- Faceted searching of discovery system.

**Comment by erinspace** [comment]
Moving out of issues - For more info and commenting, please see use case google doc - https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit
