### ISSUE TITLE
Accept: application/json on JSON API incorrectly returns HTTP 406 Error

### ISSUE THREAD

**Issue by maxogden** [CenterForOpenScience/SHARE#633]
To reproduce:

```
$ curl -H "accept: application/json" "https://share.osf.io/api/v2/normalizeddata/?format=vnd.api%2Bjson"
{"errors":[{"source":{"pointer":"/data"},"detail":"Could not satisfy the request Accept header.","status":"406"}]}
```

Remove the header and the request returns JSON as expected

**Comment by laurenbarker** [comment]
@maxogden, sorry for the delayed response. Our API follows JSON API standards so the content type for API requests would be `application/vnd.api+json` or `"accept: application/vnd.api+json"`. 

From [JSON API](http://jsonapi.org/):
> JSON API has been properly registered with the IANA. Its media type designation is application/vnd.api+json.

I'll add a JIRA ticket to make this more clear in our [documentation](http://share-research.readthedocs.io/en/latest/share_api.html#). Thank you for your feedback!
