### ISSUE TITLE
Feature Request: Link headers for pagination

### ISSUE THREAD

**Issue by maxogden** [CenterForOpenScience/SHARE#634]
To support automatic pagination tools it would be nice if the API included the standard `Link: <URL>; rel='next'` header with the link to the next page

**Comment by laurenbarker** [comment]
@maxogden, the next link is in the body of the response under `links`. This placement follows [JSON API](http://jsonapi.org/) standards. Below is an example of how you could get the next link in Python. I'll add a ticket to put this in [our docs](http://share-research.readthedocs.io/en/latest/share_api.html#) in addition to the explanation in #633. Thank you for the feedback!

```python
import requests

r = requests.get(
    'https://share.osf.io/api/v2/normalizeddata/?page=1', 
    headers={'Content-Type': 'application/vnd.api+json'}
)
next_link = r.json()['links']['next']
```
