### ISSUE TITLE
Using ?page on large result sets returns HTTP 504 Gateway Time Out

### ISSUE THREAD

**Issue by maxogden** [CenterForOpenScience/SHARE#635]
This prevents accessing data from the API. To reproduce:

```
$ curl "https://share.osf.io/api/v2/normalizeddata/?format=vnd.api%2Bjson&page=4789354"
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Using the scroll feature of elasticsearch would address this, I wrote up a proposal last year in a different repo: https://github.com/CenterForOpenScience/osf.io/issues/5658#issuecomment-222503709

**Comment by chrisseto** [comment]
@maxogden Thank you for bringing this to our attention.
We are currently not planning to make the scroll feature of elasticsearch publicly available. We are, however, investigating [more standardized ways](http://www.openarchives.org/OAI/openarchivesprotocol.html) of making the SHARE dataset programmatically accessible.

**Comment by maxogden** [comment]
> We are currently not planning to make the scroll feature of elasticsearch publicly available.

Is there a technical reason forthis?

> investigating more standardized ways of making the SHARE dataset programmatically accessible.

Great, got an open issue for that I can track/discuss on? Would be nice to have a way to download SHARE as JSON (OAI-PMH is XML)

**Comment by JeffSpies** [comment]
I'm looking into this. Thanks for raising it!

**Comment by JeffSpies** [comment]
Chris is right thought that were are considering more directed APIs outside of a mostly ES query interface.

In terms of output, unfortunately you are currently in the minority for users that want XML vs. JSON output, and we're always balancing community impact with resourcing, but we'll see what we can do right now. 

And do keep in mind that while there may be no technical reason not to do something, it doesn't mean that that thing requires no resources to do, and we balance many community priorities across many communities. :)

**Comment by maxogden** [comment]
> Chris is right thought that were are considering more directed APIs outside of a mostly ES query interface.

Does this consideration happen in public? Happy to chime in where helpful.

> In terms of output, unfortunately you are currently in the minority for users that want XML vs. JSON output, and we're always balancing community impact with resourcing, but we'll see what we can do right now.

You have more users asking for XML than JSON so you will only support XML and not support JSON for a modern web API?

> And do keep in mind that while there may be no technical reason not to do something, it doesn't mean that that thing requires no resources to do, and we balance many community priorities across many communities. :)

I agree in general, but in this specific case it seems like a pretty simple solution: expose and document the scroll feature of ElasticSearch (unless you can provide a reason not to).

**Comment by JeffSpies** [comment]
> Does this consideration happen in public? Happy to chime in where helpful.

Not as well as we could, especially with non-partner devs, but some new prioritization I'm working on focuses on that. That doc will be made public as soon as it's more than outline. Would love your feedback on it and especially engagement with the dev community.

> You have more users asking for XML than JSON so you will only support XML and not support JSON for a modern web API?

Ha, of course not although the library community would probably appreciate us more if we did. While I'm surprised the output format is such a concern, we do have a "modern web API" that speaks JSON available here:

https://share.osf.io/api/v2/

Was there a reason you didn't want to use that? Maybe it wasn't clear that it was available. 

In thinking about access to ES in the way you're suggesting when that API is available--given other priorities and load considerations--XML would have more impact, so that was in the queue before scroll, which we did just decide to rethink as Chris notes.

> I agree in general, but in this specific case it seems like a pretty simple solution: expose and document the scroll feature of ElasticSearch (unless you can provide a reason not to).

Simple can come with overhead in many forms. If I'm correct, and I might not be, scroll does allow for access in such a way that could exhaust resources on an already expensive box. Maybe that's configurable. Something we'd need to look at.

**Comment by maxogden** [comment]
> Was there a reason you didn't want to use that? Maybe it wasn't clear that it was available.

The original purpose of this issue is that the current SHARE API returns 504 errors. Therefore it is unclear if it is actually possible to download the SHARE data today. If it not available for downloading, that's okay too, I just keep getting conflicting responses. If you can point me at an example of downloading all the data through the API I would be very appreciative.

**Comment by JeffSpies** [comment]
Ah, OK. We need to figure out why you're getting that 504. @chrisseto, any thoughts?

**Comment by JeffSpies** [comment]
Seems like this is how we're doing paging and thus:

http://stackoverflow.com/questions/26625614/select-query-with-offset-limit-is-too-much-slow

We should be able to optimize that in Django, @chrisseto.

**Comment by maxogden** [comment]
I'm guessing it's because when you do a `&page=4789354` offset, ES has to re-initialize the search context and scan through the search index to that page, disregarding all intermediate pages. When you have a large number of pages, this becomes a very expensive operation, so in this case I'm guessing a timeout is hit. Exposing the scroll API would most likely reduce the load on the server for this use case, as the server could keep one search context in memory that is shared across all requests.

**Comment by chrisseto** [comment]
@maxogden paging through the API will no longer time out. We've updated [the docs](http://share-research.readthedocs.io/) to include a section on [how to page through the API](http://share-research.readthedocs.io/en/latest/share_api.html#paging-in-the-api) as well.

Thank you again for bringing this to our attention. If you encounter any more trouble, feel free to reopen this issue.

**Comment by maxogden** [comment]
Thanks! For reference here's the commit that addressed this issue: https://github.com/CenterForOpenScience/SHARE/commit/2714c1825e37284b76ea01d408965a1762566f57
