### ISSUE TITLE
Updating campus researcher profile

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#64]
An institutional policy makes it mandatory for a researcher to keep her list of publications up to date in the institution's CRIS system. Instead of filling out the metadata by hand, the research adds individual items to the CRIS based on metadata retrieved from SHARE after searching on her own name through a live lookup integration between the CRIS and SHARE.

**Layers Involved**
- Registry

**Challenges**
- Ambiguous names present problems for researchers.

**Potential Requirements**
- API for searching SHARE registry and returning the data to local CRIS for presentation.

**Comment by erinspace** [comment]
Moving out of issues - For more info and commenting, please see use case google doc - https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit
