### ISSUE TITLE
Dates in ATOM Feed

### ISSUE THREAD

**Issue by VickySteeves** [CenterForOpenScience/SHARE#646]
Hi all,

Currently, it seems like there's no date field at all in entries in a SHARE ATOM feed. For instance, when I looked at the ATOM feed for search query '[library science' on SHARE](https://share.osf.io/api/v2/atom/?elasticQuery=%7B%22query_string%22%3A%7B%22query%22%3A%22library%20science%20information%20science%22%7D%7D), the first few entries only have:

- title
- link
- id
- summary (with type="hmtl")
- category term(s)

It breaks a bunch of feed importers to not have dates. A 'date.published' field on this feed would be excellent for feedreaders and more. Thanks!

**Comment by chrisseto** [comment]
Thank you for bringing this issue to our attention.

As of 2.7.1, publication and modification dates will be included in the ATOM and RSS feeds, when available.

By default the modification date will be when SHARE last modified a given record.
If you would prefer the modification date that was reported to SHARE, add the query parameter `order=date_updated` to your URL.
Keep in mind, if a source has not reported a modification date to SHARE, it will not be included in the feed when ordering by `date_updated`.
