### ISSUE TITLE
Automatically directing SHARE data to campus profile

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#65]
The researcher registers her ORCID in the campus CRIS to make it even easier to update her profile. New notifications in SHARE bearing her ORCID now get automatically imported into her workspace for review and addition to the CRIS profile.

**Layers Involved**
- Notification Service

**Challenges**
- Campus CRIS would have to transform SHARE feed into actionable items for researcher.

**Potential Requirements**
- Widespread ORCID adoption.

**Comment by erinspace** [comment]
Moving out of issues - For more info and commenting, please see use case google doc - https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit
