### ISSUE TITLE
Facilitating worldwide collaboration

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#66]
A publisher wants to get the word out about the research release events represented by their publication, but they are not satisfied with just communicating this to a United States audience. They report these events to SHARE because of SHARE's collaborations with Jisc in the UK, OpenAIRE in Europe, and other research awareness services around the world.

**Layers Involved**
- Notification Service

**Challenges**
- Coordination with Jisc Monitor, OpenAIRE, COAR and other worldwide efforts requires ongoing effort and vigilance.

**Potential Requirements**
- Worldwide metadata and interoperation standards.

**Comment by erinspace** [comment]
Moving out of issues - For more info and commenting, please see use case google doc - https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit
