### ISSUE TITLE
ATOM feed can't handle ampersands

### ISSUE THREAD

**Issue by VickySteeves** [CenterForOpenScience/SHARE#718]
If you click into this work ([here](https://share.osf.io/preprint/46063-D46-185)) the ampersand renders in the title well. However, in the ATOM feed, you get something like this `&amp;amp;amp;` -- see here:

`<entry><title>Author Rights &amp;amp;amp; Repositories</title><link rel="alternate" href="https://share.osf.io/preprint/46063-D46-185"></link><published>2017-10-24T03:20:38+00:00</published><updated>2017-10-24T04:43:26+00:00</updated><id>https://share.osf.io/preprint/46063-D46-185</id><summary type="html">Presentation on Authors Rights &amp;amp;amp; Repositories given on a FGCU faculty webinar partnered with Taylor and Francis.</summary><category term="LIS Scholarship Archive|Social and Behavioral Sciences"></category><category term="LIS Scholarship Archive|Social and Behavioral Sciences|Library and Information Science"></category><category term="LIS Scholarship Archive|Social and Behavioral Sciences|Library and Information Science|Scholarly Communication"></category><category term="LIS Scholarship Archive|Social and Behavioral Sciences|Library and Information Science|Scholarly Publishing"></category><category term="copyright"></category><category term="scholarly communciation"></category><category term="authors rights"></category></entry>`

So the ATOM feed isn't parsing ampersands well. Just a head's up!

**Comment by remram44** [comment]
It looks like you are consistently encoding it three times instead of one 🤔 Which leads to `&amp;amp;` after decoding.

I didn't see any other entity in your feed, so I don't know if they get encoded as well (< to `&amp;amp;lt;`, presumably).

**Comment by laurenbarker** [comment]
Thanks for letting us know! I've added a ticket to our internal ticket tracking system and will close this one once it's been resolved.

**Comment by laurenbarker** [comment]
The fix for the ATOM feed encoding is planned for the next release, 2.13.0.

**Comment by laurenbarker** [comment]
2.13.0 has been released with the fix. Thanks for the report!

**Comment by remram44** [comment]
Indeed we no longer see errors in the feed. Thank you!
