### ISSUE TITLE
link to instructions for using the api gives 404 error

### ISSUE THREAD

**Issue by hannahmoro** [CenterForOpenScience/SHARE#796]
[WHAT-IS-THIS-EVEN.md](https://github.com/CenterForOpenScience/SHARE/blob/develop/WHAT-IS-THIS-EVEN.md) links to [USING-THE-API.md](https://github.com/CenterForOpenScience/SHARE/blob/develop/USING-THE-API.md). Needs to link to [how-to/use-the-api.md](https://github.com/CenterForOpenScience/SHARE/blob/develop/how-to/use-the-api.md).

**Comment by hannahmoro** [comment]
@aaxelb This is quite a small change; if you add me to the COS team and/or the SHARE repo I'm happy to open a PR and request your review.

**Comment by aaxelb** [comment]
@hannahmoro thanks! fixed in 90e3cb0519d1a05d4b8ce5034502802d4d6136f4
