### ISSUE TITLE
[consumer] Update on the ORCID API

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#95]
Jeff asked me to explore what flavor of the ORCID API (public or member) could provide us with access to a stream of updates of works. To make a long story short, it appears there is no good way to do this with any of the API options from ORCID. Below I reproduce my thread of conversation with some of the support team at ORCID.

Here's what I asked:

> I am interested in finding out what new works ORCID authors are claiming publicly so that we can make reports of these available to the SHARE Notification Service. One could think of this as a harvest of new public works, regardless of the author, but bounded by the date the author has added the work to their profile.
> 
> Is such a query possible with the ORCID API, either public or member?
> 
> I can see how to retrieve the public works from a given profile easily enough. And I can see how to search works for those matching certain criteria. But I'm have not found how to make those criteria simply the date the work was added to (or made public on) a profile.
> 
> I'd love any ideas on how to accomplish this.

Catalina at ORCID responded:

> We don't currently have a way to support the type of search you're looking for. While we do record the last modified date of the ORCID record, we don't record last modified date on items within the record.
> 
> But we do offer a couple tools to monitor ORCID activity at the premium membership level, if that's something SHARE is considering. The first is a webhooks tools that will let you know when an ORCID record you are watching is modified, more information on how that works is at http://support.orcid.org/knowledgebase/articles/230632. The other option is that premium members can get a datafile every month of all public information in the ORCID registry (as well as any limited information the member has been granted access to). You could then compare the records from one month to the next to see what works have been added.
> 
> Let me know if you'd like more information on either of these option.

I replied:

> By "premium membership" I assume you mean using the member API?
> 
> Even using the webhook you describe, would it be reasonable to watch every single ORCID for such changes?
> 
> It sounds like it may not be reasonable, so I just want to check before we dig into that.

To which Liz at ORCID responded:

> I work along with Catalina on the ORCID support team. On webhooks, the setup needed in order to register webhooks for all ORCID records would be somewhat tedious, although the notifications themselves are automated.
> 
> The bigger challenge that I see is that, at the moment, the notification sent via our webhooks doesn't tell your system what has been updated - just that something on a user's record has changed.
> 
> This was initially designed with profile systems in mind, with the intent that when a member's system receives a webhook notice, the system can then go out and read the user's ORCID record and update its own records with any new information.
> 
> We're working on revising the webhook feature so that it's more granular, allowing members to monitor changes to specific ORCID record sections, like works or funding items, but we've got quite a few other new features that we're looking to release this year, and this one is a little lower on the list.

This leaves me thinking that, while there is hope for an API that would allow us to harvest the new public works from ORCID, it is not coming any time soon. I also wonder if it would not be easier for ORCID to implement our push-in protocol once we create it. If we make that available in the next month or two, they likely won't have invested much time in the works harvest yet.

This also makes me wonder if we should be looking beyond ORCID for a self-reporting mechanism for SHARE NS. Maybe even to the OSF itself?

**Comment by laurenbarker** [comment]
Thank you for the information! Going to go ahead and close this issue.
