### ISSUE TITLE
Pointers to more about RIOXX and OpenAIRE metadata guidelines

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#96]
As I mentioned in a recent call with the developers, efforts are underway to devise a blueprint for international metadata interoperability. Katleen Shearer will even spend some time with the Technical Working Group on the Tuesday of our [SHARE Fall Meeting](http://www.arl.org/events/upcoming-events/share-2014-fall-meeting/schedule-for-share-2014-fall-meeting) to discuss this.

Meanwhile, you may want to take a look at both the [RIOXX guidelines](http://rioxx.net/v2-0-beta-1/) from the UK and the [OpenAIRE guidelines](https://guidelines.openaire.eu/wiki/OpenAIRE_Guidelines:_For_Literature_repositories) from Europe which could serve as models for our own requests of repositories and other providers to SHARE.

**Comment by laurenbarker** [comment]
Closing as this is now outdated.
